### ISSUE TITLE
App still under development?

### ISSUE THREAD

**Issue by csoltenborn** [PracticeTimeApp/PracticeTime#2]
Hi,

this is a really nice app! In fact, I had developed something similar for my private use (never got to publishing it), with rather similar (and more) functionality, and I could imagine to contribute to this app if time allows...

Couple of ideas:
- tablet support
- support for more practicing tools (despite the metronome and the recorder)
- synchronization between different devices
- more fine-grained library (ability to divide item into sections (e.g. described by providing start and end bar)
- more fine-grained goals (e.g. "practice this library item only every second day"

And on the more complex side: allow creation for practice plans for a particular piece (e.g. starting with the most difficult sections, and taking into account that often there are bars which are repeated, and thus only have to be practiced once), and let users share such plans.

**Comment by matthiasemde** [comment]
Hi Christian,

thank you for showing interest in our app! Development off the PracticeTime app is concluded and the app will stay in its current state at the wish of Javier Carbone, the product owner.

However, we, Michael and Matthias aka. the developers, are currently working on our own fork, which already includes some of your ideas and a major refactoring of the app, moving from XML to Jetpack Compose.
At the moment, both Michael and I are busy with university, but as soon as we pick up development again and get the new app released, we would love for you to contribute and bring in your ideas!

Best wishes
Matthias

**Comment by csoltenborn** [comment]
Thanks for the answer - sounds great! One followup question if I may - any chance that you already share the code? I'm curious to see what you guys are working on... Or is this going to be closed source?

**Comment by matthiasemde** [comment]
The Code is already on my GitHub! Check out the v2 and UUID branches. Although I have to warn you... the repository is in quite a mess since I left it mid refactor to focus on my masters thesis.

**Comment by csoltenborn** [comment]
Ah - sweet :-) - I didn't see a (git) clone of this repository, that's why I asked... See you there!
