### ISSUE TITLE
Export data?

### ISSUE THREAD

**Issue by EvoArt** [PracticeTimeApp/PracticeTime#3]
Love the app thanks! Is there any way (official or hacky) to export data as a CSV or the like? Ideally I would love a data file with an entry for each practice session and the following columns: time/date, practice time, rating, comments.

Any guidance would be much appreciated.

Thanks!

**Comment by matthiasemde** [comment]
Hey Arthur,

Thank you for using _PracticeTime!_

Here's the problem concerning the database export:
Android is very strict about restricting access to each app's storage from anyone but the app itself. The only way to get to the data is to either root your phone (which you probably don't want to do), or export them through the app itself. Unfortunately, we (the devs) can't publish updates for the original _PracticeTime!_ app through the Google Play Store.

However, we have the Import/Export feature build for our Upcoming _PracticeTime!_ fork called _Musikus_. I can try to build a patch for the _PracticeTime!_ app which includes this feature and publish the updated .apk here on Github. You'll have to manually install it on your phone but that should be pretty easy.
Do you think you'll be able to pull the data you want from the SQLite database and convert it to CSV yourself?
I can try and build a CSV export feature as well, but that might take a little while longer ;)

I'll keep you posted on the progress
Matthias

**Comment by matthiasemde** [comment]
Update:
I have finished the patch including the database backup feature and a CSV export function.
Unfortunately, I can't seem to find a way to update the app without the PlayStore. I have contacted Javier and asked him to grant us devs access to the GooglePlay account so I can push the updated app over the PlayStore. Wish me luck!

**Comment by EvoArt** [comment]
Wow! What an amazing response! 

Thank you so much, this is more than I could have expected. Excited to see how goes the push to the PlayStore. 🤞

Thanks again,
Arthur

P.S.

I probably could have figured out the conversion to CSV in the end, but this is so much better.
